# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
NODE_COUNT = 1 

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network :private_network, ip: "177.122.51.1"
    subconfig.vm.hostname = "master"
    subconfig.ssh.insert_key = false

    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "CentOS7_master"
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
  config.vm.provision "shell", path: "scripts/presetting.sh"
  config.vm.provision "shell", path: "scripts/master.sh"
end