apiVersion: v1
kind: Secret
metadata:
  name: specail-secret-v3
stringData:
  PASSWORD: strongpassword
  USERNAME: admin
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-volume
  namespace: my-pods-volumes-secrets-configmaps
spec:
  containers:
    - name: container
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "ls -l /etc/secrets/"]
      volumeMounts:
      - name: secrets-volume
        mountPath: /etc/secrets
  volumes:
    - name: secrets-volume
      secret:
        secretName: specail-secret-v3
  restartPolicy: Never

# kubectl get secrets