apiVersion: v1
kind: Secret
metadata:
  name: specail-config-v2
stringData:
  cert: cetificate-value
  password: password-value
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-envfrom
  namespace: my-pods-volumes-secrets-configmaps
spec:
  containers:
    - name: container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: specail-config-v2
  restartPolicy: Never