# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
HOST_IP = "192.168.101.10"

Vagrant.configure("2") do |config|
	config.vm.box = BOX_IMAGE
	config.vm.network "private_network", ip: HOST_IP
	config.vm.hostname = "gitlab"
	config.vm.provider "virtualbox" do |vb|
		vb.name = "GitLab"
		vb.cpus = 2
		vb.memory = 3072
	end

	config.vm.provision "shell", path: "scripts/settings.sh"
end