apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name-app
  namespace: my-microservice-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: name-app
    spec:
      containers:
      - name: name-app
        image: nginx:alpine
#        command: ["/bash/sh", "-c", "echo hkanonik > /usr/share/nginx/html/index.html"]
        ports:
        - name: http-name-app
          containerPort: 80

# kubectl exec -it -n my-microservice-app name-app-78cf86c4f9-rmp5b sh
# curl -H "host:hnapp.k8s.local" 192.168.56.240/author